// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/olteffe/avitochat/internal/usecase (interfaces: Chat)

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/olteffe/avitochat/internal/models"
)

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// CreateChatUseCase mocks base method.
func (m *MockChat) CreateChatUseCase(arg0 *models.Chats) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatUseCase", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatUseCase indicates an expected call of CreateChatUseCase.
func (mr *MockChatMockRecorder) CreateChatUseCase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatUseCase", reflect.TypeOf((*MockChat)(nil).CreateChatUseCase), arg0)
}

// GetChatUseCase mocks base method.
func (m *MockChat) GetChatUseCase(arg0 string) ([]*models.Chats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatUseCase", arg0)
	ret0, _ := ret[0].([]*models.Chats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatUseCase indicates an expected call of GetChatUseCase.
func (mr *MockChatMockRecorder) GetChatUseCase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatUseCase", reflect.TypeOf((*MockChat)(nil).GetChatUseCase), arg0)
}
