// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/olteffe/avitochat/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Chat is an autogenerated mock type for the Chat type
type Chat struct {
	mock.Mock
}

// CreateChatUseCase provides a mock function with given fields: chat
func (_m *Chat) CreateChatUseCase(chat *models.Chats) (string, error) {
	ret := _m.Called(chat)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.Chats) string); ok {
		r0 = rf(chat)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Chats) error); ok {
		r1 = rf(chat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChatUseCase provides a mock function with given fields: userId
func (_m *Chat) GetChatUseCase(userId string) ([]*models.Chats, error) {
	ret := _m.Called(userId)

	var r0 []*models.Chats
	if rf, ok := ret.Get(0).(func(string) []*models.Chats); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Chats)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
