// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/olteffe/avitochat/internal/usecase (interfaces: Message)

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/olteffe/avitochat/internal/models"
)

// MockMessage is a mock of Message interface.
type MockMessage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageMockRecorder
}

// MockMessageMockRecorder is the mock recorder for MockMessage.
type MockMessageMockRecorder struct {
	mock *MockMessage
}

// NewMockMessage creates a new mock instance.
func NewMockMessage(ctrl *gomock.Controller) *MockMessage {
	mock := &MockMessage{ctrl: ctrl}
	mock.recorder = &MockMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessage) EXPECT() *MockMessageMockRecorder {
	return m.recorder
}

// GetMessagesUseCase mocks base method.
func (m *MockMessage) GetMessagesUseCase(arg0 *models.Messages) ([]*models.Messages, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesUseCase", arg0)
	ret0, _ := ret[0].([]*models.Messages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesUseCase indicates an expected call of GetMessagesUseCase.
func (mr *MockMessageMockRecorder) GetMessagesUseCase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesUseCase", reflect.TypeOf((*MockMessage)(nil).GetMessagesUseCase), arg0)
}

// SendMessageUseCase mocks base method.
func (m *MockMessage) SendMessageUseCase(arg0 *models.Messages) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageUseCase", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessageUseCase indicates an expected call of SendMessageUseCase.
func (mr *MockMessageMockRecorder) SendMessageUseCase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageUseCase", reflect.TypeOf((*MockMessage)(nil).SendMessageUseCase), arg0)
}
